#! /bin/sh
bspc monitor -d Dev Dev Browse Browse Game Game Net Net Misc
bspc config border_width         3
bspc config window_gap          15

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focused_border_color \#ff79c6
bspc config normal_border_color \#6272a4
bspc config border_radius 10

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config automatic_scheme spiral

bspc rule -a Gimp desktop='^8' state=floating follow=on

# autostart programs
killall sxhkd
sxhkd &
killall picom
picom &
feh --bg-scale /home/kevin/Pictures/gentoo-dracula.png
/home/kevin/.config/polybar/launch.sh
qjackctl --start
